DELETE FROM tProductSection WHERE ISNULL(PSEC_PRIORITY,0) <> 99

INSERT INTO tPRODUCTSECTION (PSEC_P_ID,PSEC_SEC_ID,PSEC_PRIORITY)
SELECT P_ID,DICT_ID,0 FROM tPRODUCT JOIN tIMPORTSTOCK ON P_EAN = IS_EAN JOIN tDICT ON DICT_SHORT = IS_SECTIONCODE2 WHERE IS_SECTIONCODE2  IS NOT NULL

INSERT INTO tPRODUCTSECTION (PSEC_P_ID,PSEC_SEC_ID,PSEC_PRIORITY)
SELECT P_ID,DICT_ID,0 FROM tPRODUCT JOIN tIMPORTSTOCK ON P_CODE = '#' + IS_EAN JOIN tDICT ON DICT_SHORT = IS_SECTIONCODE2 WHERE IS_SECTIONCODE2  IS NOT NULL