Attribute VB_Name = "SQL"
'Option Explicit
'
'Public Const WeekPivot As String = "SELECT SUM(CASE WEEKSEQ WHEN 01 THEN QTY ELSE 0 END) AS w1, SUM(CASE WEEKSEQ WHEN 02 THEN QTY ELSE 0 END) AS w2, " _
'                      & "SUM(CASE WEEKSEQ WHEN 03 THEN QTY ELSE 0 END) AS w3, SUM(CASE WEEKSEQ WHEN 04 THEN QTY ELSE 0 END) AS w4,SUM(CASE WEEKSEQ WHEN 05 THEN QTY ELSE 0 END) AS w5, " _
'                      & "SUM(CASE WEEKSEQ WHEN 06 THEN QTY ELSE 0 END) AS w6, SUM(CASE WEEKSEQ WHEN 07 THEN QTY ELSE 0 END) AS w7, SUM(CASE WEEKSEQ WHEN 08 THEN QTY ELSE 0 END) AS w8, " _
'                      & "SUM(CASE WEEKSEQ WHEN 09 THEN QTY ELSE 0 END) AS w9, SUM(CASE WEEKSEQ WHEN 10 THEN QTY ELSE 0 END) AS w10, " _
'                      & "SUM(CASE WEEKSEQ WHEN 11 THEN QTY ELSE 0 END) AS w11, SUM(CASE WEEKSEQ WHEN 12 THEN QTY ELSE 0 END) AS w12,SUM(CASE WEEKSEQ WHEN 13 THEN QTY ELSE 0 END) AS w13, " _
'                      & "SUM(CASE WEEKSEQ WHEN 14 THEN QTY ELSE 0 END) AS w14, SUM(CASE WEEKSEQ WHEN 15 THEN QTY ELSE 0 END) AS w15, SUM(CASE WEEKSEQ WHEN 16 THEN QTY ELSE 0 END) AS w16, " _
'                      & "SUM(CASE WEEKSEQ WHEN 17 THEN QTY ELSE 0 END) AS w17, SUM(CASE WEEKSEQ WHEN 18 THEN QTY ELSE 0 END) AS w18, SUM(CASE WEEKSEQ WHEN 19 THEN QTY ELSE 0 END) AS w19, " _
'                      & "SUM(CASE WEEKSEQ WHEN 20 THEN QTY ELSE 0 END) AS w20, SUM(CASE WEEKSEQ WHEN 21 THEN QTY ELSE 0 END) AS w21, SUM(CASE WEEKSEQ WHEN 22 THEN QTY ELSE 0 END) AS w22, " _
'                      & "SUM(CASE WEEKSEQ WHEN 23 THEN QTY ELSE 0 END) AS w23, SUM(CASE WEEKSEQ WHEN 24 THEN QTY ELSE 0 END) AS w24, SUM(CASE WEEKSEQ WHEN 25 THEN QTY ELSE 0 END) AS w25, " _
'                      & "SUM(CASE WEEKSEQ WHEN 26 THEN QTY ELSE 0 END) AS w26, SUM(CASE WEEKSEQ WHEN 27 THEN QTY ELSE 0 END) AS w27, SUM(CASE WEEKSEQ WHEN 28 THEN QTY ELSE 0 END) AS w28, " _
'                      & "SUM(CASE WEEKSEQ WHEN 29 THEN QTY ELSE 0 END) AS w29, SUM(CASE WEEKSEQ WHEN 30 THEN QTY ELSE 0 END) AS w30, " _
'                      & "SUM(CASE WEEKSEQ WHEN 31 THEN QTY ELSE 0 END) AS w31, SUM(CASE WEEKSEQ WHEN 32 THEN QTY ELSE 0 END) AS w32, " _
'                      & "SUM(CASE WEEKSEQ WHEN 33 THEN QTY ELSE 0 END) AS w33, SUM(CASE WEEKSEQ WHEN 34 THEN QTY ELSE 0 END) AS w34, " _
'                      & "SUM(CASE WEEKSEQ WHEN 35 THEN QTY ELSE 0 END) AS w35, SUM(CASE WEEKSEQ WHEN 36 THEN QTY ELSE 0 END) AS w36, " _
'                      & "SUM(CASE WEEKSEQ WHEN 37 THEN QTY ELSE 0 END) AS w37, SUM(CASE WEEKSEQ WHEN 38 THEN QTY ELSE 0 END) AS w38, " _
'                      & "SUM(CASE WEEKSEQ WHEN 39 THEN QTY ELSE 0 END) AS w39, SUM(CASE WEEKSEQ WHEN 40 THEN QTY ELSE 0 END) AS w40, " _
'                      & "SUM(CASE WEEKSEQ WHEN 41 THEN QTY ELSE 0 END) AS w41, SUM(CASE WEEKSEQ WHEN 42 THEN QTY ELSE 0 END) AS w42, " _
'                      & "SUM(CASE WEEKSEQ WHEN 43 THEN QTY ELSE 0 END) AS w43, SUM(CASE WEEKSEQ WHEN 44 THEN QTY ELSE 0 END) AS w44, " _
'                      & "SUM(CASE WEEKSEQ WHEN 45 THEN QTY ELSE 0 END) AS w45, SUM(CASE WEEKSEQ WHEN 46 THEN QTY ELSE 0 END) AS w46, " _
'                      & "SUM(CASE WEEKSEQ WHEN 47 THEN QTY ELSE 0 END) AS w47, SUM(CASE WEEKSEQ WHEN 48 THEN QTY ELSE 0 END) AS w48, " _
'                      & "SUM(CASE WEEKSEQ WHEN 49 THEN QTY ELSE 0 END) AS w49, SUM(CASE WEEKSEQ WHEN 50 THEN QTY ELSE 0 END) AS w50, " _
'                      & "SUM(CASE WEEKSEQ WHEN 51 THEN QTY ELSE 0 END) AS w51, SUM(CASE WEEKSEQ WHEN 52 THEN QTY ELSE 0 END) AS w52 " _
'& " FROM vSALESBYWEEK JOIN " _
'& " tPRODUCT ON PID = P_ID "
'

