
--Insert Customers details to tTP
INSERT INTO tTP (TP_NAME,TP_ROLE,TP_INITIALS,TP_TITLE,TP_PHONE,TP_VATABLE,TP_VATNUMBER,TP_ACNO,TP_CELL,TP_TERMS,TP_CREDITLIMIT,OLDTPID)
SELECT DESCR,3,'','',tel,CASE WHEN currcode <> 0 THEN 0 ELSE 1 END,VATNumber,NUMR,MOBILE,Terms,CRLimit,ID FROM __CustomerAccounts

--Insert customer's address
INSERT INTO tADD (ADD_TP_ID,ADD_L1,ADD_L2,ADD_L3,ADD_L4,ADD_L5,ADD_PCODE,ADD_PHONE,ADD_FAX,
					ADD_EMAIL,ADD_ADDRESSEE,ADD_ORDERTo,ADD_DELTO,ADD_BILLTO,ADD_DEFAULT, OLDID)
SELECT TP_ID,ADD1,ADD2,ADD3,ADd4,ADD5,'',Tel,fax,email,CASE WHEN CONTACT > '' THEN CONTACT ELSE Descr END,1,0,1,1,ID 
		FROM __CustomerAccounts JOIN tTP ON OLDTPID = ID WHERE TP_ROLE = 3

--Insert second customer's address
INSERT INTO tADD (ADD_TP_ID,ADD_L1,ADD_L2,ADD_L3,ADD_L4,ADD_L5,ADD_ADDRESSEE,ADD_ORDERTo,ADD_DELTO,ADD_BILLTO,ADD_DEFAULT, OLDID)
SELECT TP_ID,delADD1,delADD2,delADD3,delADd4,deladd5,CASE WHEN CONTACT > '' THEN CONTACT ELSE Descr END,0,1,0,0,ID 
		FROM __CustomerAccounts JOIN tTP ON OLDTPID = ID WHERE TP_ROLE = 3
