--Import _POL to tTR
INSERT INTO tTR ( TR_Code, TR_TP_ID, TR_COMP_ID, TR_Status, TR_Date, TR_CaptureDate, TR_Type)
SELECT DISTINCT __POL.DOCNO, tTP.TP_ID, 1, 3, __POL.dte, __POL.dte, 5
FROM __POL INNER JOIN tTP ON __POL.ACC = tTP.TP_ACNo
WHERE (((tTP.TP_Role)=2));

--Create rows in tPO
INSERT INTO tPO ( PO_ID, PO_OrderType, PO_ShowVAT, PO_CURR_ID )
SELECT tTR.TR_ID, 1, 1, tConfiguration.CF_LocalCurrID
FROM tConfiguration, tTR
WHERE tTR.TR_Type=5

INSERT INTO tPOL(POL_TR_ID,POL_P_ID,POL_PRICE,POL_QTYFIRM,POL_QTYSS,POL_Ref,POL_FULFILLED,POL_ETA,POL_Note,POL_VATRATE) 
(SELECT TRID,PID,PRICE * 100,QTY,0,OrderRef,'OS',DATEADD(mm,1,dte),Note,14 FROM __vLoadPols)



--Import _COL to tTR
INSERT INTO tTR ( TR_Code, TR_TP_ID, TR_COMP_ID, TR_Status, TR_Date, TR_CaptureDate, TR_Type )
SELECT DISTINCT __COL.DOCNO, tTP.TP_ID, 1, 3, __COL.dte, __COL.dte, 6
FROM __COL INNER JOIN tTP ON __COL.ACC = tTP.TP_ACNo
WHERE (((tTP.TP_Role)=3));

--Create rows in tCO
INSERT INTO tCO ( CO_ID, CO_OrderType, CO_ETA)
SELECT tTR.TR_ID, 1, DATEADD(mm,1,TR_DATE)
FROM tConfiguration, tTR
WHERE tTR.TR_Type=6

INSERT INTO tCOL(COL_TR_ID,COL_P_ID,COL_PRICE,COL_QTY,COL_QTYDISPATCHED,COL_Ref,COL_FULFILLED,COL_DEPOSIT,COL_QTYFIRM,COL_NOTE) 
(SELECT TRID,PID,PRICE * 100,QTY,0,OrderRef,'OS',0,QTY,Note FROM __vLoadCols)
